[project]
name = "taofi-analyzer"
version = "2.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.1.1",
    "dash-ag-grid>=31.3.1",
    "dash-bootstrap-components>=2.0.3",
    "dataclasses-json>=0.6.7",
    "gunicorn>=23.0.0",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "plotly>=6.2.0",
    "tomli; python_version < '3.11'",
]

[dependency-groups]
dev = ["basedpyright>=1.29.5", "ruff>=0.12.2"]
